platform :ios, '12.0'
use_frameworks!

target 'DemoActivityIndicator_Example' do
  pod 'DemoActivityIndicator', :path => '../'

  target 'DemoActivityIndicator_Tests' do
    inherit! :search_paths

    
  end
end
